=== ekaplan69/FOCUS360/focus-parent/focus-rdm/src/main/resources/rdm/rdm_configuration_schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
  <xs:element name="artifact" type="artifactDeliverable" />
  <xs:element name="artifactdependencies" type="artifactDependencies" />
  <xs:element name="composite" type="compositeDeliverable" />
  <xs:element name="file" type="fileDeliverable" />
  <xs:element name="textfile" type="textfileDeliverable" />
  <xs:element name="http" type="httpDeliverable" />
  <xs:element name="batch" type="batchDeliverable" />
  <xs:element name="metadata" type="metadataDeliverable" />
  <xs:element name="textmetadata" type="textTemplateDeliverableMetadata" />
  <xs:element name="servicekatalogcsv" type="servicekatalogMetadata" />
  <xs:element name="rdmPaketConfiguration" type="paketConfiguration" />
  <xs:complexType name="paketConfiguration" final="extension restriction">
	<xs:sequence>
	  <xs:element name="unused" type="unusedConfiguration" minOccurs="0" />
	  <xs:element name="deliverable" type="deliverableConfiguration" minOccurs="0" maxOccurs="unbounded" />
	  <xs:element name="workflow" type="workflowConfiguration" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
  </xs:complexType>
  <xs:complexType name="unusedConfiguration" final="extension restriction">
	<xs:sequence>
	  <xs:element name="key" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
  </xs:complexType>
  <xs:complexType name="deliverableConfiguration" final="extension restriction">
	<xs:sequence>
	  <xs:element name="key" type="xs:string" />
	  <xs:element name="filename" type="xs:string" minOccurs="0" />
	  <xs:group ref="deliverableChoice" minOccurs="1" />
	  <xs:group ref="deliverableMetadataChoice" minOccurs="0" />
	</xs:sequence>
  </xs:complexType>
  <xs:complexType name="workflowConfiguration" final="extension restriction">
	<xs:all>
	  <xs:element name="name" type="xs:string" />
	  <xs:element name="abschnitt" type="xs:string" />
	  <xs:element name="umgebung" type="xs:string" minOccurs="0" />
	  <xs:element name="runmode" type="WorkflowRunmode" minOccurs="0" />
	  <xs:element name="properties" type="xs:string" minOccurs="0" />
	  <xs:element name="umgebung" type="xs:string" minOccurs="0" />
	</xs:all>
	<xs:attribute name="id" type="xs:string" use="required" />
  </xs:complexType>
  <xs:simpleType name="WorkflowRunmode">
	<xs:restriction base="xs:string">
	  <xs:enumeration value="Normal" />
	  <xs:enumeration value="Retroactive" />
	  <xs:enumeration value="Simulated" />
	</xs:restriction>
  </xs:simpleType>
  <xs:complexType name="deliverableType" abstract="true">
	<xs:attribute name="id" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="formattableDeliverableType" abstract="true">
	<xs:complexContent>
	  <xs:extension base="deliverableType">
		<xs:sequence>
		  <xs:element name="lineending" type="lineEndingType" minOccurs="0" />
		</xs:sequence>
	  </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  <xs:complexType name="compositeDeliverable">
	<xs:complexContent>
	  <xs:extension base="deliverableType">
		<xs:sequence>
		  <xs:element name="filename" type="xs:string" minOccurs="1" />
		  <xs:element name="type" type="xs:string" minOccurs="0" />
		  <xs:element name="elements" minOccurs="0">
			<xs:complexType>
			  <xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="element">
				  <xs:complexType>
					<xs:sequence>
					  <xs:element name="filename" type="xs:string" minOccurs="0" />
					  <xs:group ref="deliverableChoice" minOccurs="1" />
					</xs:sequence>
					<xs:attribute name="path" type="xs:string" />
				  </xs:complexType>
				</xs:element>
			  </xs:sequence>
			</xs:complexType>
		  </xs:element>
		</xs:sequence>
	  </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  <xs:complexType name="fileDeliverable" final="extension restriction">
	<xs:complexContent>
	  <xs:extension base="formattableDeliverableType">
		<xs:sequence>
		  <xs:element name="path" type="xs:string" />
		</xs:sequence>
	  </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  <xs:complexType name="textfileDeliverable" final="extension restriction">
	<xs:complexContent>
	  <xs:extension base="formattableDeliverableType">
		<xs:sequence>
		  <xs:element name="filename" type="xs:string" />
		  <xs:element name="content" type="xs:string" />
		</xs:sequence>
	  </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  <xs:complexType name="httpDeliverable" final="extension restriction">
	<xs:complexContent>
	  <xs:extension base="formattableDeliverableType">
		<xs:sequence>
		  <xs:element name="url" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
		  <xs:element name="username" type="xs:string" minOccurs="0" />
		  <xs:element name="password" type="xs:string" minOccurs="0" />
		</xs:sequence>
	  </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  <xs:complexType name="artifactDependencies">
	<xs:complexContent>
	  <xs:extension base="deliverableType">
		<xs:all>
		  <xs:element name="groupId" type="xs:string" />
		  <xs:element name="artifactId" type="xs:string" />
		  <xs:element name="version" type="xs:string" minOccurs="0" />
		  <xs:element name="type" type="xs:string" />
		  <xs:element name="classifier" type="xs:string" minOccurs="0" />
		  <xs:element name="scope" type="xs:string" default="runtime" minOccurs="0" />
		  <xs:element name="filtertype" type="xs:string" default="jar" minOccurs="0" />
		</xs:all>
	  </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  <xs:complexType name="artifactDeliverable">
	<xs:complexContent>
	  <xs:extension base="deliverableType">
		<xs:all>
		  <xs:element name="groupId" type="xs:string" />
		  <xs:element name="artifactId" type="xs:string" />
		  <xs:element name="version" type="xs:string" minOccurs="0" />
		  <xs:element name="type" type="xs:string" />
		  <xs:element name="classifier" type="xs:string" minOccurs="0" />
		</xs:all>
	  </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  <xs:complexType name="metadataDeliverable">
	<xs:complexContent>
	  <xs:extension base="deliverableType" />
	</xs:complexContent>
  </xs:complexType>
  <xs:complexType name="batchDeliverable">
	<xs:complexContent>
	  <xs:extension base="compositeDeliverable">
		<xs:sequence>
		  <xs:element name="groupId" type="xs:string" minOccurs="1" />
		  <xs:element name="artifactId" type="xs:string" minOccurs="1" />
		  <xs:element name="version" type="xs:string" minOccurs="0" />
		  <xs:element name="artifactname" type="xs:string" minOccurs="0" />
		  <xs:element name="revision" type="xs:string" minOccurs="0" />
		  <xs:element name="basepath" type="xs:string" minOccurs="0" />
		  <xs:element name="libpath" type="xs:string" minOccurs="0" default="/lib" />
		  <xs:element name="artifactpath" type="xs:string" minOccurs="0" default="/lib" />
		  <xs:element name="binpath" type="xs:string" minOccurs="0" default="/bin" />
		  <xs:element name="confpath" type="xs:string" minOccurs="0" default="/conf" />
		  <xs:element name="lineending" type="lineEndingType" minOccurs="0" />
		  <xs:element name="configurations" minOccurs="0">
			<xs:complexType>
			  <xs:group ref="deliverableChoice" maxOccurs="unbounded" />
			</xs:complexType>
		  </xs:element>
		  <xs:element name="binaries" minOccurs="0">
			<xs:complexType>
			  <xs:group ref="deliverableChoice" maxOccurs="unbounded" />
			</xs:complexType>
		  </xs:element>
		</xs:sequence>
	  </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  <xs:group name="deliverableChoice">
	<xs:choice>
	  <xs:choice>
		<xs:element ref="composite" />
		<xs:element ref="file" />
		<xs:element ref="artifact" />
		<xs:element ref="http" />
		<xs:element ref="textfile" />
		<xs:element ref="artifactdependencies" />
		<xs:element ref="batch" />
		<xs:element ref="metadata" />
	  </xs:choice>
	  <xs:any />
	</xs:choice>
  </xs:group>
  <xs:simpleType name="lineEndingType">
	<xs:restriction base="xs:string">
	  <xs:enumeration value="keep" />
	  <xs:enumeration value="windows" />
	  <xs:enumeration value="unix" />
	</xs:restriction>
  </xs:simpleType>
  <xs:complexType name="deliverableMetadataType" abstract="true" />
  <xs:complexType name="textTemplateDeliverableMetadata">
	<xs:complexContent>
	  <xs:extension base="deliverableMetadataType">
		<xs:sequence>
		  <xs:element name="template" type="xs:string" />
		  <xs:element name="replacement" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
			  <xs:sequence>
				<xs:element name="key" type="xs:string" />
				<xs:element name="text" type="xs:string" minOccurs="0" />
				<xs:element name="subpart" minOccurs="0" maxOccurs="unbounded" type="textTemplateDeliverableMetadata" />
			  </xs:sequence>
			</xs:complexType>
		  </xs:element>
		</xs:sequence>
	  </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  <xs:complexType name="servicekatalogMetadata">
	<xs:complexContent>
	  <xs:extension base="deliverableMetadataType">
		<xs:sequence>
		  <xs:element name="productname" type="xs:string" minOccurs="1" />
		  <xs:element name="systemname" type="xs:string" minOccurs="0" />
		  <xs:group ref="deliverableChoice" minOccurs="0" />
		</xs:sequence>
	  </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  <xs:group name="deliverableMetadataChoice">
	<xs:choice>
	  <xs:choice>
		<xs:element ref="textmetadata" />
		<xs:element ref="servicekatalogcsv" />
	  </xs:choice>
	  <xs:any />
	</xs:choice>
  </xs:group>
</xs:schema>

=== ekaplan69/FOCUS360/focus-parent/focus-rdm/src/main/resources/rdm/focus-config.xml
<?xml version="1.0" encoding="utf-8"?>
<rdmPaketConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rdm_configuration_schema.xsd">
  <!-- ************************************************************* -->
  <!-- Definition/Konfiguration der Deliverables/Liefergegenstaende -->
  <!-- ************************************************************* -->
  <unused>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Inbetriebnahme:Produktinf. Komp. allgem.</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Integration:Produktinf. Komp. allgem.</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Sonstiges:Produktinf. Komp. allgem.</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Integration:Produktinf. Komp. allgem.</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Qualitaetsmanagement:Produktinf. Komp. allgem.</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Lieferung:Produktinf. Komp. allgem./Batchdokumentation:Produktinf. Komp. allgem.</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Lieferung:Produktinf. Komp. allgem./Produktionsfreigabe:Produktinf. Komp. allgem.</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Lieferung:Produktinf. Komp. allgem./RDM Fragenkatalog:RDM Fragenkatalog</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Lieferung:Produktinf. Komp. allgem./Schnittstellendokumentation:Produktinf. Komp. allgem.</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Lieferung:Produktinf. Komp. allgem./Sonstige Dokumentation:Produktinf. Komp. allgem.</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Lieferung:Produktinf. Komp. allgem./SW Architekturdiagramm:SW Architektur</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Lieferung:Produktinf. Komp. allgem./Technische Releasenotes:Release Notes</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Umgebungsmanagement:Produktinf. Komp. allgem./IBN Drehbuch:IBN Drehbuch</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Umgebungsmanagement:Produktinf. Komp. allgem./IBN Fragenkatalog:IBN Fragenkatalog</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Umgebungsmanagement:Produktinf. Komp. allgem./Konfigurationskonzept:Konfigurationskonzept</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Umgebungsmanagement:Produktinf. Komp. allgem./SLA Anforderungen:SLA Anforderung</key>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Umgebungsmanagement:Produktinf. Komp. allgem./Supportkonzept:Supportkonzept</key>
	<key>Andere/Produktversion:Produktversion/Servicekatalog:Servicekatalog</key>
	<key>Andere/Produktversion:Produktversion/Abhängigkeiten:Applikationskomponente allgemein</key>
	<key>Andere/Produktversion:Produktversion/Abhängigkeiten:Applikationskomponente allgemein/Produktabhängigkeiten:Produktabhängigkeit</key>
	<key>Andere/Produktversion:Produktversion/Abhängigkeiten:Applikationskomponente allgemein/Serviceabhängigkeiten:Serviceabhängigkeit</key>
	<key>Andere/Produktversion:Produktversion/Abhängigkeiten:Applikationskomponente allgemein/Umgebungsabhängigkeiten:Umgebungsabhängigkeit</key>
  </unused>
  <!-- frontend -->
  <deliverable>
	<key>Andere/Produktversion:Produktversion/Frontend:Applikationskomponente allgemein</key>
	<artifact id="focus.frontend">
	  <groupId>at.sozvers.noegkk.focus</groupId>
	  <artifactId>focus-frontend-eportal</artifactId>
	  <classifier>delivery</classifier>
	  <type>zip</type>
	</artifact>
  </deliverable>
  <!-- db -->
  <deliverable>
	<key>Andere/Produktversion:Produktversion/Datenbank:Applikationskomponente allgemein</key>
	<artifact id="focus.db">
	  <groupId>at.sozvers.noegkk.focus</groupId>
	  <artifactId>focus-db-delivery</artifactId>
	  <classifier>db-delivery</classifier>
	  <type>zip</type>
	</artifact>
  </deliverable>
  <!-- fachliche releasenotes -->
  <deliverable>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Lieferung:Produktinf. Komp. allgem./Fachliche Releasenotes:Release Notes</key>
	<artifact id="focus.release.notes">
	  <groupId>at.sozvers.noegkk.focus</groupId>
	  <artifactId>focus-doc</artifactId>
	  <classifier>release-notes</classifier>
	  <type>pdf</type>
	</artifact>
  </deliverable>
  <!-- Installationshandbuch -->
  <deliverable>
	<key>Andere/Produktinformation:Produktinformation/Dokumentation:Produktinf. Komponente/Umgebungsmanagement:Produktinf. Komp. allgem./Installationshandbuch:Installationshandbuch</key>
	<artifact id="focus.install.manual">
	  <groupId>at.sozvers.noegkk.focus</groupId>
	  <artifactId>focus-doc</artifactId>
	  <classifier>install-manual</classifier>
	  <type>pdf</type>
	</artifact>
  </deliverable>
  <!-- ************************************************************* -->
  <!-- Workflow Definition -->
  <!-- ************************************************************* -->
  <workflow id="focus.workflow.lieferung">
	<name>FOCUS360 Lieferworkflow</name>
	<abschnitt>Lieferung</abschnitt>
  </workflow>
</rdmPaketConfiguration>
